openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /:
    get:
      tags:
      - index-controller
      operationId: get
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/IndexResource'
    post:
      tags:
      - index-controller
      operationId: post
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/IndexResource'
components:
  schemas:
    IndexResource:
      type: object
      properties:
        message:
          type: string
