spring:
  application:
    name: spring-boot-kotlin-example
springdoc:
  swagger-ui:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
  endpoint:
    prometheus:
      enabled: true
